-- Prospect audit results for the self-running Outreach Engine.
create table if not exists public.prospect_audits (
  slug text primary key,
  name text, city text, vertical text, domain text,
  rank int, count int, score int, field_avg int,
  leads boolean default false,
  top_gap text, dmarc text,
  competitors jsonb default '[]'::jsonb,
  updated_at timestamptz not null default now()
);
alter table public.prospect_audits enable row level security;
-- No anon policies: reads/writes go through the server (service-role) only.

insert into public.prospect_audits
  (slug,name,city,vertical,domain,rank,count,score,field_avg,leads,top_gap,dmarc,competitors) values
('acaciadentalgroup-com','Acacia Dental Group','Englewood','Dental','acaciadentalgroup.com',3,9,81,64,false,'A couple of web-security headers are missing','reject','[{"name":"Pacific Dental Services","domain":"www.pacificdentalservices.com","score":90},{"name":"Sopris Smiles","domain":"www.soprissmiles.com","score":82},{"name":"Colorado Dental Wellness Center","domain":"coloradodentalwellness.com","score":75},{"name":"Corson Dentistry","domain":"corsondentistry.com","score":71},{"name":"Comfort Dental","domain":"comfortdental.com","score":67},{"name":"Paradise Dentistry & Orthodontics","domain":"www.paradisedentistryorthodenver.com","score":66},{"name":"Cody Dental Group","domain":"www.codydental.com","score":37},{"name":"Happy Canyon Dental","domain":"www.happycanyondental.com","score":9}]'::jsonb),
('araoent-com','South Denver ENT & Allergy','Littleton','Medical','araoent.com',5,9,73,76,false,'Missing web-security headers (clickjacking & content protections)','quarantine','[{"name":"Planned Parenthood","domain":"www.plannedparenthood.org","score":88},{"name":"MedNow Clinic","domain":"www.mednowclinics.com","score":87},{"name":"Colorado Eye Consultants","domain":"www.coloradoeyeconsultants.com","score":84},{"name":"Associates of Otolaryngology","domain":"www.denvercoloradoearnosethroatallergysinusdoctors.com","score":74},{"name":"AFC Urgent Care","domain":"www.carenow.com","score":70},{"name":"Swedish Cancer Care Center","domain":"swedishhospital.com","score":70},{"name":"Conceptions RMA","domain":"www.conceptionsrepro.com","score":70},{"name":"Continuum Autism Spectrum Alliance Denver","domain":"www.autismspectrumalliance.com","score":70}]'::jsonb),
('aspenfallslandscaping-com','Aspen Falls Landscape & Const.','Centennial','Landscape','aspenfallslandscaping.com',3,7,80,70,false,'No DMARC record — your email domain can be impersonated','','[{"name":"Garden Supply","domain":"genhydro.com","score":86},{"name":"Epic Lawn Pro","domain":"www.epiclawnpro.com","score":85},{"name":"The Bronze Petal","domain":"www.thebronzepetal.com","score":73},{"name":"Walmart Garden Center","domain":"www.walmart.com","score":66},{"name":"Denver Landscape Company","domain":"denverlandscapecompany.com","score":56},{"name":"Tagawa Gardens","domain":"www.tagawagardens.com","score":45}]'::jsonb),
('attorneysofhighlandsranch-com','Town & Town (Attorneys of HR)','Highlands Ranch','Legal','attorneysofhighlandsranch.com',5,7,58,68,false,'No DMARC record — your email domain can be impersonated','','[{"name":"Law Offices of M. Colin Bresee","domain":"bresee.com","score":90},{"name":"The Littleton Law Office of Bahr, Kreidle & Flicker","domain":"littletonlawyers.com","score":75},{"name":"Plog & Stein, P.C.","domain":"www.plogsteinlaw.com","score":72},{"name":"Griffiths Law PC","domain":"www.griffithslawpc.com","score":70},{"name":"Colorado Trusts & Taxes","domain":"cotruststaxes.com","score":57},{"name":"The Boyle Law Firm","domain":"www.boyleinjurylaw.com","score":56}]'::jsonb),
('biondijewelry-com','Biondi Diamond Jewelers','Aurora','E-commerce','biondijewelry.com',1,6,87,65,true,'DMARC isn''t enforced (p=none) — your email can be spoofed by scammers','none','[{"name":"Pandora","domain":"pandoraonthehill.com","score":81},{"name":"Diamond Mine","domain":"dmjewelry.com","score":63},{"name":"Len Larson Jewelry","domain":"lenlarson.com","score":63},{"name":"Denver Crystals & Gems","domain":"www.denvercrystalsandgems.com","score":54},{"name":"Colorado Diamonds and Design","domain":"www.coloradodiamondsanddesign.com","score":44}]'::jsonb),
('buildabath-net','Build A Bath & Kitchen','Highlands Ranch','Remodeling','buildabath.net',1,6,94,85,true,'DMARC isn''t enforced (p=none) — your email can be spoofed by scammers','none','[{"name":"Mini U Storage","domain":"www.miniustorage.com","score":92},{"name":"Extra Space Storage","domain":"extraspace.com","score":88},{"name":"Public Storage","domain":"www.publicstorage.com","score":84},{"name":"The Home Depot","domain":"www.homedepot.com","score":81},{"name":"Print & Copy Centers of Colorado","domain":"www.printandcopyco.com","score":68}]'::jsonb),
('castlerockcpa-com','Castle Rock CPA','Castle Rock','Accounting','castlerockcpa.com',1,6,81,68,true,'DMARC isn''t enforced (p=none) — your email can be spoofed by scammers','none','[{"name":"SBA CPA","domain":"thesbacpa.com","score":78},{"name":"Steven J Wick & Associates PC","domain":"sjwickcpa.com","score":73},{"name":"AuerCPA","domain":"auercpa.com","score":69},{"name":"Profiscal Solutions","domain":"profiscalsolutions.com","score":63},{"name":"Evergreen CPAs","domain":"evergreencpas.com","score":41}]'::jsonb),
('cherryhillsdentist-com','Cherry Hills Dental Associates','Englewood','Dental','cherryhillsdentist.com',7,9,41,60,false,'DMARC isn''t enforced (p=none) — your email can be spoofed by scammers','none','[{"name":"Pacific Dental Services","domain":"www.pacificdentalservices.com","score":90},{"name":"Sopris Smiles","domain":"www.soprissmiles.com","score":82},{"name":"Colorado Dental Wellness Center","domain":"coloradodentalwellness.com","score":75},{"name":"Corson Dentistry","domain":"corsondentistry.com","score":71},{"name":"Comfort Dental","domain":"comfortdental.com","score":67},{"name":"Paradise Dentistry & Orthodontics","domain":"www.paradisedentistryorthodenver.com","score":66},{"name":"Cody Dental Group","domain":"www.codydental.com","score":37},{"name":"Happy Canyon Dental","domain":"www.happycanyondental.com","score":9}]'::jsonb),
('clchr-org','Christ Lutheran Church','Highlands Ranch','Church','clchr.org',3,9,77,66,false,'DMARC isn''t enforced (p=none) — your email can be spoofed by scammers','none','[{"name":"Pax Christi Catholic Church","domain":"paxchristi.org","score":84},{"name":"Connections Church","domain":"myconnections.church","score":79},{"name":"Saint Timothy''s Episcopal Church","domain":"www.sttims.net","score":69},{"name":"Legacy Chapel","domain":"legacychapel.org","score":66},{"name":"Highlands Baptist Church","domain":"www.highlandsbaptistchurch.org","score":66},{"name":"Abiding Word Lutheran Church","domain":"www.awlc.org","score":57},{"name":"St. Luke''s United Methodist Church","domain":"stlukeshr.com","score":56},{"name":"Denver Colorado Temple","domain":"www.churchofjesuschrist.org","score":40}]'::jsonb),
('coloradodermatology-com','Dermatology & Laser Institute','Lone Tree','Medical','coloradodermatology.com',8,8,23,63,false,'No proper HTTPS — browsers can warn visitors your site isn''t secure','none','[{"name":"National Jewish Health Highlands Ranch","domain":"www.nationaljewish.org","score":80},{"name":"Castle Rock Hormone Health","domain":"crhormonehealth.com","score":77},{"name":"South Denver Gastroenterology","domain":"southdenvergi.com","score":70},{"name":"Locketz Facial Plastic Surgery","domain":"www.locketzfacialplastics.com","score":70},{"name":"Integrated Ear Nose and Throat","domain":"www.integratedent.com","score":64},{"name":"Austin Brown Podiatry & Wound Care","domain":"www.abpwc.com","score":60},{"name":"Robinson Cosmetic Surgery, LLC","domain":"www.robinsoncosmeticsurgery.com","score":56}]'::jsonb),
('coloradolendingteam-com','Colorado Lending Team','Englewood','Mortgage','coloradolendingteam.com',5,6,61,69,false,'DMARC isn''t enforced (p=none) — your email can be spoofed by scammers','none','[{"name":"Brighton Jones","domain":"www.brightonjones.com","score":87},{"name":"Mosaic Retirement Planning, LLC","domain":"www.mosaicretirementplanning.com","score":73},{"name":"Edward Jones","domain":"www.edwardjones.com","score":71},{"name":"Riser Accounting","domain":"www.riseraccounting.com","score":67},{"name":"JPL Wealth Management","domain":"www.jplwm.com","score":52}]'::jsonb),
('compfm-com','Comprehensive Family Medicine','Highlands Ranch','Medical','compfm.com',7,7,9,67,false,'No proper HTTPS — browsers can warn visitors your site isn''t secure','','[{"name":"Planned Parenthood","domain":"www.plannedparenthood.org","score":88},{"name":"Colorado Eye Consultants","domain":"www.coloradoeyeconsultants.com","score":84},{"name":"Children''s Hospital Colorado Therapy Care, Highlands Ranch","domain":"www.childrenscolorado.org","score":82},{"name":"National Jewish Health Highlands Ranch","domain":"www.nationaljewish.org","score":80},{"name":"Conceptions RMA","domain":"www.conceptionsrepro.com","score":70},{"name":"OnPoint Urgent Care","domain":"www.onpointurgentcare.com","score":56}]'::jsonb),
('copelandfamilydental-com','Copeland Family Dental','Highlands Ranch','Dental','copelandfamilydental.com',4,9,78,70,false,'Missing web-security headers (clickjacking & content protections)','reject','[{"name":"Pacific Dental Services","domain":"www.pacificdentalservices.com","score":90},{"name":"Sopris Smiles","domain":"www.soprissmiles.com","score":82},{"name":"Dentists of Littleton","domain":"www.dentistsoflittleton.com","score":80},{"name":"303 Dental Group Amy Roberts DDS, PLLC","domain":"303dentalgroup.com","score":73},{"name":"Clear Smile Dental Care","domain":"www.cleardentalcentennial.com","score":72},{"name":"Comfort Dental","domain":"comfortdental.com","score":67},{"name":"Secora Family Dentistry","domain":"www.secoradentistry.com","score":52},{"name":"Chatfield Smiles Dentistry","domain":"chatfieldsmiles.com","score":39}]'::jsonb),
('cotitleescrow-com','Colorado Title & Escrow','Parker','Title/Escrow','cotitleescrow.com',1,5,78,58,true,'A couple of web-security headers are missing','reject','[{"name":"Kris Kellar Coldwell Banker","domain":"parkercoloradohousesforsale.com","score":60},{"name":"Mountain Financial Mortgage Group","domain":"mfmloans.com","score":53},{"name":"Beattie Team - Alliance Mortgage Group","domain":"www.amglending.com","score":53},{"name":"Tasha Beckman - EXIT Mosaic Realty | Mama Bear Team","domain":"www.exitmosaicrealty.com","score":45}]'::jsonb),
('denverfamilylawmatters-com','Tolison & Williams','Brighton','Legal','denverfamilylawmatters.com',1,3,80,76,true,'DMARC isn''t enforced (p=none) — your email can be spoofed by scammers','none','[{"name":"Catherine Brown, LLC","domain":"www.cbrownlaw.com","score":78},{"name":"The Murphy Law Firm","domain":"www.brianmurphy.net","score":70}]'::jsonb),
('elevatemyeyes-com','Highlands Ranch Vision Center','Highlands Ranch','Optometry','elevatemyeyes.com',1,7,89,70,true,'A couple of web-security headers are missing','quarantine','[{"name":"Great Western Lodging","domain":"gwlodging.com","score":87},{"name":"Envision Eye Care","domain":"envision-eyecare.com","score":83},{"name":"Copeland Family Dental","domain":"copelandfamilydental.com","score":78},{"name":"Highlands Family Chiropractic","domain":"highlandsfamilychiropractic.com","score":75},{"name":"Highlands Ranch Family Dentistry","domain":"hrfamilydentistry.com","score":68},{"name":"Comprehensive Family Medicine","domain":"compfm.com","score":9}]'::jsonb),
('equippedchurch-net','Equipped Church','Highlands Ranch','Church','equippedchurch.net',1,9,86,68,true,'DMARC isn''t enforced (p=none) — your email can be spoofed by scammers','none','[{"name":"Pax Christi Catholic Church","domain":"paxchristi.org","score":84},{"name":"Connections Church","domain":"myconnections.church","score":79},{"name":"Christ Lutheran Church","domain":"www.clchr.org","score":75},{"name":"Legacy Chapel","domain":"legacychapel.org","score":66},{"name":"Highlands Baptist Church","domain":"www.highlandsbaptistchurch.org","score":66},{"name":"Abiding Word Lutheran Church","domain":"www.awlc.org","score":57},{"name":"St. Luke''s United Methodist Church","domain":"stlukeshr.com","score":56},{"name":"Denver Colorado Temple","domain":"www.churchofjesuschrist.org","score":40}]'::jsonb),
('firmmedspa-com','The Firm Medspa','Lone Tree','Med Spa','firmmedspa.com',8,8,39,67,false,'No proper HTTPS — browsers can warn visitors your site isn''t secure','none','[{"name":"Planned Parenthood","domain":"www.plannedparenthood.org","score":88},{"name":"National Jewish Health Highlands Ranch","domain":"www.nationaljewish.org","score":80},{"name":"Castle Rock Hormone Health","domain":"crhormonehealth.com","score":77},{"name":"South Denver Gastroenterology","domain":"southdenvergi.com","score":70},{"name":"Integrated Ear Nose and Throat","domain":"www.integratedent.com","score":64},{"name":"Austin Brown Podiatry & Wound Care","domain":"www.abpwc.com","score":60},{"name":"Robinson Cosmetic Surgery, LLC","domain":"www.robinsoncosmeticsurgery.com","score":56}]'::jsonb),
('griffithslawpc-com','Griffiths Law PC','Lone Tree','Legal','griffithslawpc.com',3,9,75,70,false,'Missing web-security headers (clickjacking & content protections)','quarantine','[{"name":"Law Offices of M. Colin Bresee","domain":"bresee.com","score":90},{"name":"Robinson & Henry, P.C.","domain":"www.robinsonandhenry.com","score":76},{"name":"The Littleton Law Office of Bahr, Kreidle & Flicker","domain":"littletonlawyers.com","score":75},{"name":"Plog & Stein, P.C.","domain":"www.plogsteinlaw.com","score":72},{"name":"Palmer Family Law","domain":"www.palmerfamilylawco.com","score":70},{"name":"Andrew T. Brake, P.C.","domain":"www.brakelaw.com","score":61},{"name":"Colorado Trusts & Taxes","domain":"cotruststaxes.com","score":57},{"name":"The Boyle Law Firm","domain":"www.boyleinjurylaw.com","score":56}]'::jsonb),
('heidiosterobgyn-com','Dr. Heidi Oster, MD (OB/GYN)','Lone Tree','Medical','heidiosterobgyn.com',6,8,63,70,false,'No DMARC record — your email domain can be impersonated','','[{"name":"Planned Parenthood","domain":"www.plannedparenthood.org","score":88},{"name":"National Jewish Health Highlands Ranch","domain":"www.nationaljewish.org","score":80},{"name":"Castle Rock Hormone Health","domain":"crhormonehealth.com","score":77},{"name":"South Denver Gastroenterology","domain":"southdenvergi.com","score":70},{"name":"Integrated Ear Nose and Throat","domain":"www.integratedent.com","score":64},{"name":"Austin Brown Podiatry & Wound Care","domain":"www.abpwc.com","score":60},{"name":"Robinson Cosmetic Surgery, LLC","domain":"www.robinsoncosmeticsurgery.com","score":56}]'::jsonb),
('homesteadtc-com','Homestead Title & Escrow','Greenwood Village','Title/Escrow','homesteadtc.com',4,8,75,69,false,'Missing web-security headers (clickjacking & content protections)','quarantine','[{"name":"Hurl & Hurl Insurance Agency","domain":"davidhurl.net","score":87},{"name":"Fred Loya Insurance","domain":"www.fredloya.com","score":86},{"name":"Covered Insurance","domain":"itscovered.com","score":81},{"name":"State Farm","domain":"www.statefarm.com","score":72},{"name":"Stailey Insurance","domain":"www.staileycorp.com","score":62},{"name":"C-M Car Insurance","domain":"alluscarinsurance.com","score":46},{"name":"Chad Thielen: Allstate Insurance","domain":"agents.allstate.com","score":45}]'::jsonb),
('hrcoc-org','Highlands Ranch Church of Christ','Highlands Ranch','Church','hrcoc.org',4,9,71,66,false,'No DMARC record — your email domain can be impersonated','','[{"name":"Pax Christi Catholic Church","domain":"paxchristi.org","score":84},{"name":"Connections Church","domain":"myconnections.church","score":79},{"name":"Christ Lutheran Church","domain":"www.clchr.org","score":75},{"name":"Legacy Chapel","domain":"legacychapel.org","score":66},{"name":"Highlands Baptist Church","domain":"www.highlandsbaptistchurch.org","score":66},{"name":"Abiding Word Lutheran Church","domain":"www.awlc.org","score":57},{"name":"St. Luke''s United Methodist Church","domain":"stlukeshr.com","score":56},{"name":"Denver Colorado Temple","domain":"www.churchofjesuschrist.org","score":40}]'::jsonb),
('kcmortgagecolorado-com','KC Mortgage (Kay Cleland)','Castle Rock','Mortgage','kcmortgagecolorado.com',2,6,82,65,true,'DMARC isn''t enforced (p=none) — your email can be spoofed by scammers','none','[{"name":"Bowman Financial Strategies","domain":"www.bowmanfinancialstrategies.com","score":87},{"name":"Mosaic Retirement Planning, LLC","domain":"www.mosaicretirementplanning.com","score":73},{"name":"Mountain Financial Mortgage Group","domain":"mfmloans.com","score":53},{"name":"Beattie Team - Alliance Mortgage Group","domain":"www.amglending.com","score":53},{"name":"Three Peaks Capital Management","domain":"www.threepeaks.com","score":40}]'::jsonb),
('mckeanins-com','McKean Insurance Agency','Parker','Insurance','mckeanins.com',1,8,85,70,true,'Missing web-security headers (clickjacking & content protections)','reject','[{"name":"State Farm","domain":"www.matthewfry.net","score":77},{"name":"State Farm","domain":"theparkeragent.com","score":75},{"name":"Farmers Insurance - Troy Gardner","domain":"agents.farmers.com","score":73},{"name":"Lucy Buck State Farm Insurance","domain":"www.lucybuck.com","score":71},{"name":"State Farm","domain":"krististearns.com","score":67},{"name":"Kirsch Insurance","domain":"ikirsch.com","score":57},{"name":"Gerald L Lukton Co","domain":"luktoncompany.com","score":57}]'::jsonb),
('milehighsmilesandesthetics-com','Mile High Smiles & Esthetics','Lone Tree','Dental','milehighsmilesandesthetics.com',8,8,9,65,false,'No proper HTTPS — browsers can warn visitors your site isn''t secure','','[{"name":"Smile Doctors Braces","domain":"www.smiledoctors.com","score":91},{"name":"My Kid’s Dentist and Orthodontics","domain":"www.mykidsdentistlonetree.com","score":80},{"name":"Lone Tree Dentist","domain":"www.lonetreedentalgroup.com","score":80},{"name":"Comfort Dental","domain":"www.comfortdentalkids.com","score":76},{"name":"Redd Orthodontics","domain":"www.reddortho.com","score":75},{"name":"Highlands Ranch Smiles","domain":"highlandsranchcoloradodentist.com","score":71},{"name":"Highlands Ranch Dental Group","domain":"highlandsranchdentalgroup.com","score":39}]'::jsonb),
('missionhills-org','Mission Hills Church','Castle Rock','Church','missionhills.org',2,9,77,65,false,'DMARC isn''t enforced (p=none) — your email can be spoofed by scammers','none','[{"name":"Sanctuary Christian Fellowship","domain":"www.scf.church","score":91},{"name":"Saint Timothy''s Episcopal Church","domain":"www.sttims.net","score":69},{"name":"Congregation Beth Shalom","domain":"www.cbsdenver.org","score":68},{"name":"Family Worship Center","domain":"www.fwcenter.org","score":64},{"name":"First Presbyterian Church of Englewood","domain":"1stpresenglewood.org","score":64},{"name":"Saint Louis Catholic Church","domain":"www.stlouiscatholicparish.org","score":55},{"name":"Our Lady of Mount Carmel Catholic Church","domain":"www.olmcfssp.org","score":49},{"name":"Saint Herman Orthodox Church","domain":"www.sthermanoca.org","score":49}]'::jsonb),
('montessoriatlonetree-com','Montessori School at Lone Tree','Lone Tree','Childcare/Edu','montessoriatlonetree.com',7,9,70,75,false,'No DMARC record — your email domain can be impersonated','','[{"name":"New Horizon Academy","domain":"newhorizonacademy.net","score":90},{"name":"SkyView Academy","domain":"www.skyviewacademy.org","score":89},{"name":"cms.dcsdk12.org","domain":"cms.dcsdk12.org","score":85},{"name":"Eagle Academy","domain":"ea.dcsdk12.org","score":85},{"name":"Mountain Ridge Middle School","domain":"mrms.dcsdk12.org","score":85},{"name":"Arrowwood Elementary School","domain":"awe.dcsdk12.org","score":75},{"name":"Highlands Ranch High School","domain":"www.hrhsfalcons.com","score":58},{"name":"Saint Thomas More Catholic School","domain":"www.stmcatholic.org","score":36}]'::jsonb),
('myrkmhome-com','RKM Homes','Castle Rock','Custom builder','myrkmhome.com',2,7,86,73,true,'No DMARC record — your email domain can be impersonated','','[{"name":"Coleman Custom Homes","domain":"cchvail.com","score":87},{"name":"Westover Construction","domain":"westoverconstruction.com","score":79},{"name":"Stone Aspen Signature Builders","domain":"stoneaspen.com","score":77},{"name":"Premier Mountain Builders","domain":"premiermountainbuilders.com","score":74},{"name":"Kinley Built","domain":"kinleybuilt.com","score":56},{"name":"ULFBUILT","domain":"ulfbuilt.com","score":53}]'::jsonb),
('new3c-org','New Covenant Community Church','Highlands Ranch','Church','new3c.org',7,7,29,65,false,'DMARC isn''t enforced (p=none) — your email can be spoofed by scammers','none','[{"name":"Sanctuary Christian Fellowship","domain":"www.scf.church","score":91},{"name":"Greenwood Community Church","domain":"greenwoodcc.com","score":71},{"name":"Saint Timothy''s Episcopal Church","domain":"www.sttims.net","score":69},{"name":"Congregation Beth Shalom","domain":"www.cbsdenver.org","score":68},{"name":"Family Worship Center","domain":"www.fwcenter.org","score":64},{"name":"First Presbyterian Church of Englewood","domain":"1stpresenglewood.org","score":64}]'::jsonb),
('niedermaninsurance-com','Niederman Insurance Agency','Highlands Ranch','Insurance','niedermaninsurance.com',2,8,86,72,true,'DMARC isn''t enforced (p=none) — your email can be spoofed by scammers','none','[{"name":"Premier Group Insurance Corporate Office","domain":"www.thinkpremierfirst.com","score":91},{"name":"State Farm","domain":"theparkeragent.com","score":75},{"name":"Farmers Insurance - Troy Gardner","domain":"agents.farmers.com","score":73},{"name":"Lucy Buck State Farm Insurance","domain":"www.lucybuck.com","score":71},{"name":"State Farm","domain":"krististearns.com","score":67},{"name":"Gerald L Lukton Co","domain":"luktoncompany.com","score":57},{"name":"Kirsch Insurance","domain":"ikirsch.com","score":57}]'::jsonb),
('originalhardware-com','originalhardware-com','','','',1,6,90,79,true,'DMARC isn''t enforced (p=none) — your email can be spoofed by scammers','none','[{"name":"Mountain Standard Goods","domain":"mstgoods.com","score":85},{"name":"White Oak Boutique","domain":"thewhiteoakboutique.com","score":83},{"name":"ElseWear Collective","domain":"elsewearcollective.com","score":82},{"name":"Shirt Off My Back","domain":"shirtoffmybacklittleton.com","score":82},{"name":"J Claire Women''s Fashion","domain":"jclairewomensfashion.com","score":54}]'::jsonb),
('paramounttitle-com','Paramount Title Agency','Greenwood Village','Title/Escrow','paramounttitle.com',1,6,91,63,true,'No DMARC record — your email domain can be impersonated','','[{"name":"Farmers Insurance - Troy Gardner","domain":"agents.farmers.com","score":73},{"name":"Lucy Buck State Farm Insurance","domain":"www.lucybuck.com","score":71},{"name":"Stailey Insurance","domain":"www.staileycorp.com","score":62},{"name":"Gerald L Lukton Co","domain":"luktoncompany.com","score":57},{"name":"CoWest Insurance Associates","domain":"www.cowestassociates.com","score":23}]'::jsonb),
('paxchristi-org','Pax Christi Catholic Community','Lone Tree','Church','paxchristi.org',3,8,84,76,false,'No DMARC record — your email domain can be impersonated','','[{"name":"Bethany Lutheran Church (ELCA)","domain":"bethany-denver.org","score":94},{"name":"Temple Sinai","domain":"www.sinaidenver.org","score":87},{"name":"Greenwood Community Church","domain":"greenwoodcc.com","score":71},{"name":"Saint Timothy''s Episcopal Church","domain":"www.sttims.net","score":69},{"name":"Congregation Hebrew Educational Alliance","domain":"headenver.org","score":69},{"name":"Congregation Beth Shalom","domain":"www.cbsdenver.org","score":68},{"name":"Family Worship Center","domain":"www.fwcenter.org","score":64}]'::jsonb),
('rosslawcolorado-com','Ross Law PC','Centennial','Legal','rosslawcolorado.com',1,8,90,75,true,'DMARC isn''t enforced (p=none) — your email can be spoofed by scammers','none','[{"name":"Law Offices of M. Colin Bresee","domain":"bresee.com","score":90},{"name":"www.m2lawyers.com","domain":"www.m2lawyers.com","score":86},{"name":"The Wilhite Law Firm - Personal Injury Attorney","domain":"www.wilhitelawfirm.com","score":76},{"name":"Plog & Stein, P.C.","domain":"www.plogsteinlaw.com","score":72},{"name":"Griffiths Law PC","domain":"www.griffithslawpc.com","score":70},{"name":"Andrew T. Brake, P.C.","domain":"www.brakelaw.com","score":61},{"name":"Colorado Trusts & Taxes","domain":"cotruststaxes.com","score":57}]'::jsonb),
('smokyhillumc-org','Smoky Hill United Methodist Church','Centennial','Church','smokyhillumc.org',1,9,84,74,true,'A couple of web-security headers are missing','reject','[{"name":"Saint Catherine Greek Orthodox Church","domain":"stcatherinechurch.org","score":79},{"name":"National Fire & Safety","domain":"natfiresafety.com","score":77},{"name":"Saint Thomas More Catholic Church","domain":"stthomasmore.org","score":76},{"name":"Covenant Presbyterian DTC","domain":"covenantdtc.org","score":75},{"name":"Hope United Methodist Church","domain":"www.hopechangeslives.org","score":73},{"name":"Church of Christ of Cherry Vista","domain":"www.cherryvistachurchofchrist.org","score":70},{"name":"Aish Denver","domain":"aishdenver.com","score":70},{"name":"Red Rocks Church","domain":"www.redrockschurch.com","score":66}]'::jsonb),
('southdenverobgyn-com','South Denver OB/GYN & Midwives','Littleton','Medical','southdenverobgyn.com',4,7,61,58,false,'Missing web-security headers (clickjacking & content protections)','reject','[{"name":"Associates of Otolaryngology","domain":"www.denvercoloradoearnosethroatallergysinusdoctors.com","score":74},{"name":"Swedish Cancer Care Center","domain":"swedishhospital.com","score":70},{"name":"Continuum Autism Spectrum Alliance Denver","domain":"www.autismspectrumalliance.com","score":70},{"name":"OnPoint Urgent Care","domain":"www.onpointurgentcare.com","score":56},{"name":"Rutledge Psychiatry","domain":"www.rutledgemd.com","score":43},{"name":"Foothills Family Practice","domain":"www.foothillsfamilypractice.com","score":31}]'::jsonb),
('southwestheating-com','Southwest Heating & Cooling','Littleton','HVAC','southwestheating.com',3,9,77,68,false,'DMARC isn''t enforced (p=none) — your email can be spoofed by scammers','none','[{"name":"Simply Mechanical AC, Furnace & Boiler Repair","domain":"simplymechanicalco.com","score":83},{"name":"Fireside Heating and Cooling","domain":"www.firesidehvac.com","score":81},{"name":"Littleton Hot Water Heaters LLC","domain":"littletonhotwaterheater.com","score":76},{"name":"Befort Plumbing & Heating","domain":"www.befortplumbingandheating.com","score":71},{"name":"Premier Electrical Staffing","domain":"www.premierelectricalstaffing.com","score":65},{"name":"Defense Plumbing","domain":"www.defenseplumbing.com","score":60},{"name":"Master Rooter","domain":"masterrooter.plumbing","score":60},{"name":"Odin Electric","domain":"odinelec.com","score":41}]'::jsonb),
('stoneaspen-com','Stone Aspen Signature Builders','Castle Rock','Custom builder','stoneaspen.com',4,7,77,73,false,'No DMARC record — your email domain can be impersonated','','[{"name":"Coleman Custom Homes","domain":"cchvail.com","score":87},{"name":"RKM Homes","domain":"myrkmhome.com","score":86},{"name":"Westover Construction","domain":"westoverconstruction.com","score":79},{"name":"Premier Mountain Builders","domain":"premiermountainbuilders.com","score":74},{"name":"Kinley Built","domain":"kinleybuilt.com","score":56},{"name":"ULFBUILT","domain":"ulfbuilt.com","score":53}]'::jsonb),
('summitchurch-online','Summit Church','Centennial','Church','summitchurch.online',6,8,68,74,false,'DMARC isn''t enforced (p=none) — your email can be spoofed by scammers','none','[{"name":"Bethany Lutheran Church (ELCA)","domain":"bethany-denver.org","score":94},{"name":"Temple Sinai","domain":"www.sinaidenver.org","score":87},{"name":"Greenwood Community Church","domain":"greenwoodcc.com","score":71},{"name":"Saint Timothy''s Episcopal Church","domain":"www.sttims.net","score":69},{"name":"Congregation Hebrew Educational Alliance","domain":"headenver.org","score":69},{"name":"Congregation Beth Shalom","domain":"www.cbsdenver.org","score":68},{"name":"Family Worship Center","domain":"www.fwcenter.org","score":64}]'::jsonb),
('thrivechurch-com','Thrive Church','Lone Tree','Church','thrivechurch.com',1,8,94,69,true,'DMARC isn''t enforced (p=none) — your email can be spoofed by scammers','none','[{"name":"Equipped Church","domain":"equippedchurch.net","score":86},{"name":"Mile High Calvary","domain":"milehighcalvary.com","score":85},{"name":"Cherry Hills Community Church","domain":"chcc.org","score":73},{"name":"Highlands Ranch Church of Christ","domain":"hrcoc.org","score":71},{"name":"St. Mark Catholic Church","domain":"stmarkhr.org","score":63},{"name":"Castle Rock Community Church","domain":"visitcrcc.org","score":54},{"name":"New Covenant Community Church","domain":"new3c.org","score":29}]'::jsonb),
('truebeautymedspa-com','True Beauty Med Spa','Littleton','Med Spa','truebeautymedspa.com',4,9,82,77,false,'No DMARC record — your email domain can be impersonated','','[{"name":"Planned Parenthood","domain":"www.plannedparenthood.org","score":88},{"name":"MedNow Clinic","domain":"www.mednowclinics.com","score":87},{"name":"Colorado Eye Consultants","domain":"www.coloradoeyeconsultants.com","score":84},{"name":"Associates of Otolaryngology","domain":"www.denvercoloradoearnosethroatallergysinusdoctors.com","score":74},{"name":"AFC Urgent Care","domain":"www.carenow.com","score":70},{"name":"Swedish Cancer Care Center","domain":"swedishhospital.com","score":70},{"name":"Conceptions RMA","domain":"www.conceptionsrepro.com","score":70},{"name":"Continuum Autism Spectrum Alliance Denver","domain":"www.autismspectrumalliance.com","score":70}]'::jsonb),
('vaughn-law-com','The Vaughn Law Offices, PLLC','Lone Tree','Legal','vaughn-law.com',6,6,77,84,false,'No DMARC record — your email domain can be impersonated','','[{"name":"The McKenzie Law Firm","domain":"themckenziefirm.com","score":94},{"name":"Colorado Estate Matters","domain":"coloradoestatematters.com","score":87},{"name":"Antommaria Ilevska Elder LLC","domain":"arcoloradolaw.com","score":87},{"name":"Law Office of Anna L. Burr","domain":"burr-law.com","score":79},{"name":"Goodman and Wallace PC","domain":"goodmanwallace.com","score":78}]'::jsonb),
('visitcrcc-org','Castle Rock Community Church','Castle Rock','Church','visitcrcc.org',4,6,54,61,false,'No DMARC record — your email domain can be impersonated','','[{"name":"Saint Francis of Assisi Catholic Church","domain":"www.stfranciscr.org","score":79},{"name":"Faith Life Fellowship","domain":"faithlifefellowship.us","score":71},{"name":"New Hope Presbyterian Church","domain":"www.newhopepres.org","score":71},{"name":"Epiphany Lutheran Church","domain":"epiphanylc.org","score":53},{"name":"The Connection Church of Nazarene","domain":"connectionnaz.org","score":39}]'::jsonb),
('wamboltwealth-com','Wambolt & Associates (RIA)','Littleton','Finance','wamboltwealth.com',3,6,79,74,false,'Missing web-security headers (clickjacking & content protections)','quarantine','[{"name":"Brighton Jones","domain":"www.brightonjones.com","score":87},{"name":"Fidelity Investments","domain":"www.fidelity.com","score":80},{"name":"Mosaic Retirement Planning, LLC","domain":"www.mosaicretirementplanning.com","score":73},{"name":"Edward Jones","domain":"www.edwardjones.com","score":71},{"name":"JPL Wealth Management","domain":"www.jplwm.com","score":52}]'::jsonb)
on conflict (slug) do update set
  name=excluded.name, city=excluded.city, vertical=excluded.vertical, domain=excluded.domain,
  rank=excluded.rank, count=excluded.count, score=excluded.score, field_avg=excluded.field_avg,
  leads=excluded.leads, top_gap=excluded.top_gap, dmarc=excluded.dmarc, competitors=excluded.competitors,
  updated_at=now();
